baseURL = 'https://www.pptjuego.com/'
#languageCode = 'en-us'
title = 'Hector Sab'
theme = 'ananke'
defaultContentLanguage = "en"

[menu]
[[menu.main]]
    pageRef = "about"
    name = "About"
    weight = 20

[languages]
[languages.en]
    weight = 1

[languages.es]
    weight = 2
    [[languages.es.menu.main]]
        pageRef = "about"
        name = "Acerca de"


[params]
[[params.ananke_socials]]
    name = "mastodon"
    url = "https://mastodon.online/@hector_sab"
    rel = "me noopener"

[[params.ananke_socials]]
    name = "twitter"
    url = "https://twitter.com/hector_sab"

[[params.ananke_socials]]
    name = "github"
    url = "https://github.com/hector-sab"

[permalinks]
    pages = "/:title/"
